fix

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -129,14 +129,15 @@ steps:
           echo "URL map $_SERVICE_NAME-url-map already exists. Skipping creation.";
         fi
 
-  # Adjuntar NEG para la región primaria
+    # Adjuntar NEG para la región primaria
   - id: attach-neg-primary
     name: 'ubuntu'
     entrypoint: 'bash'
     args:
       - '-c'
       - |
-        apt-get update && apt-get install -y jq && \
+        apt-get update -y && apt-get install -y jq && \
+        which jq || { echo "Error: jq no está disponible después de la instalación"; exit 1; } && \
         echo "Verificando si el NEG $_SERVICE_NAME-primary ya está adjunto al servicio backend $_SERVICE_NAME-backend..." && \
         if gcloud compute backend-services describe $_SERVICE_NAME-backend --global --format="json" | jq -r '.backends[].group' | grep -q "https://compute.googleapis.com/compute/v1/projects/$_PROJECT_ID/regions/$_PRIMARY_REGION/networkEndpointGroups/$_SERVICE_NAME-primary"; then
           echo "NEG $_SERVICE_NAME-primary ya está adjunto al servicio backend $_SERVICE_NAME-backend. Omitiendo."
@@ -146,15 +147,15 @@ steps:
             --network-endpoint-group $_SERVICE_NAME-primary \
             --network-endpoint-group-region $_PRIMARY_REGION
         fi
-
-  # Adjuntar NEG para la región secundaria
+    # Adjuntar NEG para la región secundaria
   - id: attach-neg-secondary
     name: 'ubuntu'
     entrypoint: 'bash'
     args:
       - '-c'
       - |
-        apt-get update && apt-get install -y jq && \
+        apt-get update -y && apt-get install -y jq && \
+        which jq || { echo "Error: jq no está disponible después de la instalación"; exit 1; } && \
         echo "Verificando si el NEG $_SERVICE_NAME-secondary ya está adjunto al servicio backend $_SERVICE_NAME-backend..." && \
         if gcloud compute backend-services describe $_SERVICE_NAME-backend --global --format="json" | jq -r '.backends[].group' | grep -q "https://compute.googleapis.com/compute/v1/projects/$_PROJECT_ID/regions/$_SECONDARY_REGION/networkEndpointGroups/$_SERVICE_NAME-secondary"; then
           echo "NEG $_SERVICE_NAME-secondary ya está adjunto al servicio backend $_SERVICE_NAME-backend. Omitiendo."
@@ -164,6 +165,7 @@ steps:
             --network-endpoint-group $_SERVICE_NAME-secondary \
             --network-endpoint-group-region $_SECONDARY_REGION
         fi
+
 
   # Configure traffic splitting
   - id: configure-traffic-splitting
